// (C) 2010 Arsène von Wyss / bsn
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Xml;
using System.Xml.XPath;

using bsn.GoldParser.Grammar;
using bsn.GoldParser.Parser;
using bsn.GoldParser.Semantic;
using bsn.ModuleStore.Sql.Script;

namespace bsn.ModuleStore.Sql {
	public static class ScriptParser {
		// XML document found at %ProgramFiles(x86)%\Microsoft SQL Server\90\Tools\binn\VSShell\Common7\IDE\SqlToolsData\1033\
		private static readonly XPathDocument commonObjects = LoadCommonObjectsXml();

		// reserved word list: http://msdn.microsoft.com/en-us/library/aa238507(v=SQL.80).aspx
		private static readonly HashSet<string> reservedWords = new HashSet<string>(StringComparer.OrdinalIgnoreCase) {
		                                                                                                              		"ADD",
		                                                                                                              		"EXCEPT",
		                                                                                                              		"PERCENT",
		                                                                                                              		"ALL",
		                                                                                                              		"EXEC",
		                                                                                                              		"PLAN",
		                                                                                                              		"ALTER",
		                                                                                                              		"EXECUTE",
		                                                                                                              		"PRECISION",
		                                                                                                              		"AND",
		                                                                                                              		"EXISTS",
		                                                                                                              		"PRIMARY",
		                                                                                                              		"ANY",
		                                                                                                              		"EXIT",
		                                                                                                              		"PRINT",
		                                                                                                              		"AS",
		                                                                                                              		"FETCH",
		                                                                                                              		"PROC",
		                                                                                                              		"ASC",
		                                                                                                              		"FILE",
		                                                                                                              		"PROCEDURE",
		                                                                                                              		"AUTHORIZATION",
		                                                                                                              		"FILLFACTOR",
		                                                                                                              		"PUBLIC",
		                                                                                                              		"BACKUP",
		                                                                                                              		"FOR",
		                                                                                                              		"RAISERROR",
		                                                                                                              		"BEGIN",
		                                                                                                              		"FOREIGN",
		                                                                                                              		"READ",
		                                                                                                              		"BETWEEN",
		                                                                                                              		"FREETEXT",
		                                                                                                              		"READTEXT",
		                                                                                                              		"BREAK",
		                                                                                                              		"FREETEXTTABLE",
		                                                                                                              		"RECONFIGURE",
		                                                                                                              		"BROWSE",
		                                                                                                              		"FROM",
		                                                                                                              		"REFERENCES",
		                                                                                                              		"BULK",
		                                                                                                              		"FULL",
		                                                                                                              		"REPLICATION",
		                                                                                                              		"BY",
		                                                                                                              		"FUNCTION",
		                                                                                                              		"RESTORE",
		                                                                                                              		"CASCADE",
		                                                                                                              		"GOTO",
		                                                                                                              		"RESTRICT",
		                                                                                                              		"CASE",
		                                                                                                              		"GRANT",
		                                                                                                              		"RETURN",
		                                                                                                              		"CHECK",
		                                                                                                              		"GROUP",
		                                                                                                              		"REVOKE",
		                                                                                                              		"CHECKPOINT",
		                                                                                                              		"HAVING",
		                                                                                                              		"RIGHT",
		                                                                                                              		"CLOSE",
		                                                                                                              		"HOLDLOCK",
		                                                                                                              		"ROLLBACK",
		                                                                                                              		"CLUSTERED",
		                                                                                                              		"IDENTITY",
		                                                                                                              		"ROWCOUNT",
		                                                                                                              		"COALESCE",
		                                                                                                              		"IDENTITY_INSERT",
		                                                                                                              		"ROWGUIDCOL",
		                                                                                                              		"COLLATE",
		                                                                                                              		"IDENTITYCOL",
		                                                                                                              		"RULE",
		                                                                                                              		"COLUMN",
		                                                                                                              		"IF",
		                                                                                                              		"SAVE",
		                                                                                                              		"COMMIT",
		                                                                                                              		"IN",
		                                                                                                              		"SCHEMA",
		                                                                                                              		"COMPUTE",
		                                                                                                              		"INDEX",
		                                                                                                              		"SELECT",
		                                                                                                              		"CONSTRAINT",
		                                                                                                              		"INNER",
		                                                                                                              		"SESSION_USER",
		                                                                                                              		"CONTAINS",
		                                                                                                              		"INSERT",
		                                                                                                              		"SET",
		                                                                                                              		"CONTAINSTABLE",
		                                                                                                              		"INTERSECT",
		                                                                                                              		"SETUSER",
		                                                                                                              		"CONTINUE",
		                                                                                                              		"INTO",
		                                                                                                              		"SHUTDOWN",
		                                                                                                              		"CONVERT",
		                                                                                                              		"IS",
		                                                                                                              		"SOME",
		                                                                                                              		"CREATE",
		                                                                                                              		"JOIN",
		                                                                                                              		"STATISTICS",
		                                                                                                              		"CROSS",
		                                                                                                              		"KEY",
		                                                                                                              		"SYSTEM_USER",
		                                                                                                              		"CURRENT",
		                                                                                                              		"KILL",
		                                                                                                              		"TABLE",
		                                                                                                              		"CURRENT_DATE",
		                                                                                                              		"LEFT",
		                                                                                                              		"TEXTSIZE",
		                                                                                                              		"CURRENT_TIME",
		                                                                                                              		"LIKE",
		                                                                                                              		"THEN",
		                                                                                                              		"CURRENT_TIMESTAMP",
		                                                                                                              		"LINENO",
		                                                                                                              		"TO",
		                                                                                                              		"CURRENT_USER",
		                                                                                                              		"LOAD",
		                                                                                                              		"TOP",
		                                                                                                              		"CURSOR",
		                                                                                                              		"NATIONAL",
		                                                                                                              		"TRAN",
		                                                                                                              		"DATABASE",
		                                                                                                              		"NOCHECK",
		                                                                                                              		"TRANSACTION",
		                                                                                                              		"DBCC",
		                                                                                                              		"NONCLUSTERED",
		                                                                                                              		"TRIGGER",
		                                                                                                              		"DEALLOCATE",
		                                                                                                              		"NOT",
		                                                                                                              		"TRUNCATE",
		                                                                                                              		"DECLARE",
		                                                                                                              		"NULL",
		                                                                                                              		"TSEQUAL",
		                                                                                                              		"DEFAULT",
		                                                                                                              		"NULLIF",
		                                                                                                              		"UNION",
		                                                                                                              		"DELETE",
		                                                                                                              		"OF",
		                                                                                                              		"UNIQUE",
		                                                                                                              		"DENY",
		                                                                                                              		"OFF",
		                                                                                                              		"UPDATE",
		                                                                                                              		"DESC",
		                                                                                                              		"OFFSETS",
		                                                                                                              		"UPDATETEXT",
		                                                                                                              		"DISK",
		                                                                                                              		"ON",
		                                                                                                              		"USE",
		                                                                                                              		"DISTINCT",
		                                                                                                              		"OPEN",
		                                                                                                              		"USER",
		                                                                                                              		"DISTRIBUTED",
		                                                                                                              		"OPENDATASOURCE",
		                                                                                                              		"VALUES",
		                                                                                                              		"DOUBLE",
		                                                                                                              		"OPENQUERY",
		                                                                                                              		"VARYING",
		                                                                                                              		"DROP",
		                                                                                                              		"OPENROWSET",
		                                                                                                              		"VIEW",
		                                                                                                              		"DUMMY",
		                                                                                                              		"OPENXML",
		                                                                                                              		"WAITFOR",
		                                                                                                              		"DUMP",
		                                                                                                              		"OPTION",
		                                                                                                              		"WHEN",
		                                                                                                              		"ELSE",
		                                                                                                              		"OR",
		                                                                                                              		"WHERE",
		                                                                                                              		"END",
		                                                                                                              		"ORDER",
		                                                                                                              		"WHILE",
		                                                                                                              		"ERRLVL",
		                                                                                                              		"OUTER",
		                                                                                                              		"WITH",
		                                                                                                              		"ESCAPE",
		                                                                                                              		"OVER",
		                                                                                                              		"WRITETEXT",
		                                                                                                              		"ABSOLUTE",
		                                                                                                              		"EXEC",
		                                                                                                              		"OVERLAPS",
		                                                                                                              		"ACTION",
		                                                                                                              		"EXECUTE",
		                                                                                                              		"PAD",
		                                                                                                              		"ADA",
		                                                                                                              		"EXISTS",
		                                                                                                              		"PARTIAL",
		                                                                                                              		"ADD",
		                                                                                                              		"EXTERNAL",
		                                                                                                              		"PASCAL",
		                                                                                                              		"ALL",
		                                                                                                              		"EXTRACT",
		                                                                                                              		"POSITION",
		                                                                                                              		"ALLOCATE",
		                                                                                                              		"FALSE",
		                                                                                                              		"PRECISION",
		                                                                                                              		"ALTER",
		                                                                                                              		"FETCH",
		                                                                                                              		"PREPARE",
		                                                                                                              		"AND",
		                                                                                                              		"FIRST",
		                                                                                                              		"PRESERVE",
		                                                                                                              		"ANY",
		                                                                                                              		"FLOAT",
		                                                                                                              		"PRIMARY",
		                                                                                                              		"ARE",
		                                                                                                              		"FOR",
		                                                                                                              		"PRIOR",
		                                                                                                              		"AS",
		                                                                                                              		"FOREIGN",
		                                                                                                              		"PRIVILEGES",
		                                                                                                              		"ASC",
		                                                                                                              		"FORTRAN",
		                                                                                                              		"PROCEDURE",
		                                                                                                              		"ASSERTION",
		                                                                                                              		"FOUND",
		                                                                                                              		"PUBLIC",
		                                                                                                              		"AT",
		                                                                                                              		"FROM",
		                                                                                                              		"READ",
		                                                                                                              		"AUTHORIZATION",
		                                                                                                              		"FULL",
		                                                                                                              		"REAL",
		                                                                                                              		"AVG",
		                                                                                                              		"GET",
		                                                                                                              		"REFERENCES",
		                                                                                                              		"BEGIN",
		                                                                                                              		"GLOBAL",
		                                                                                                              		"RELATIVE",
		                                                                                                              		"BETWEEN",
		                                                                                                              		"GO",
		                                                                                                              		"RESTRICT",
		                                                                                                              		"BIT",
		                                                                                                              		"GOTO",
		                                                                                                              		"REVOKE",
		                                                                                                              		"BIT_LENGTH",
		                                                                                                              		"GRANT",
		                                                                                                              		"RIGHT",
		                                                                                                              		"BOTH",
		                                                                                                              		"GROUP",
		                                                                                                              		"ROLLBACK",
		                                                                                                              		"BY",
		                                                                                                              		"HAVING",
		                                                                                                              		"ROWS",
		                                                                                                              		"CASCADE",
		                                                                                                              		"HOUR",
		                                                                                                              		"SCHEMA",
		                                                                                                              		"CASCADED",
		                                                                                                              		"IDENTITY",
		                                                                                                              		"SCROLL",
		                                                                                                              		"CASE",
		                                                                                                              		"IMMEDIATE",
		                                                                                                              		"SECOND",
		                                                                                                              		"CAST",
		                                                                                                              		"IN",
		                                                                                                              		"SECTION",
		                                                                                                              		"CATALOG",
		                                                                                                              		"INCLUDE",
		                                                                                                              		"SELECT",
		                                                                                                              		"CHAR",
		                                                                                                              		"INDEX",
		                                                                                                              		"SESSION",
		                                                                                                              		"CHAR_LENGTH",
		                                                                                                              		"INDICATOR",
		                                                                                                              		"SESSION_USER",
		                                                                                                              		"CHARACTER",
		                                                                                                              		"INITIALLY",
		                                                                                                              		"SET",
		                                                                                                              		"CHARACTER_LENGTH",
		                                                                                                              		"INNER",
		                                                                                                              		"SIZE",
		                                                                                                              		"CHECK",
		                                                                                                              		"INPUT",
		                                                                                                              		"SMALLINT",
		                                                                                                              		"CLOSE",
		                                                                                                              		"INSENSITIVE",
		                                                                                                              		"SOME",
		                                                                                                              		"COALESCE",
		                                                                                                              		"INSERT",
		                                                                                                              		"SPACE",
		                                                                                                              		"COLLATE",
		                                                                                                              		"INT",
		                                                                                                              		"SQL",
		                                                                                                              		"COLLATION",
		                                                                                                              		"INTEGER",
		                                                                                                              		"SQLCA",
		                                                                                                              		"COLUMN",
		                                                                                                              		"INTERSECT",
		                                                                                                              		"SQLCODE",
		                                                                                                              		"COMMIT",
		                                                                                                              		"INTERVAL",
		                                                                                                              		"SQLERROR",
		                                                                                                              		"CONNECT",
		                                                                                                              		"INTO",
		                                                                                                              		"SQLSTATE",
		                                                                                                              		"CONNECTION",
		                                                                                                              		"IS",
		                                                                                                              		"SQLWARNING",
		                                                                                                              		"CONSTRAINT",
		                                                                                                              		"ISOLATION",
		                                                                                                              		"SUBSTRING",
		                                                                                                              		"CONSTRAINTS",
		                                                                                                              		"JOIN",
		                                                                                                              		"SUM",
		                                                                                                              		"CONTINUE",
		                                                                                                              		"KEY",
		                                                                                                              		"SYSTEM_USER",
		                                                                                                              		"CONVERT",
		                                                                                                              		"LANGUAGE",
		                                                                                                              		"TABLE",
		                                                                                                              		"CORRESPONDING",
		                                                                                                              		"LAST",
		                                                                                                              		"TEMPORARY",
		                                                                                                              		"COUNT",
		                                                                                                              		"LEADING",
		                                                                                                              		"THEN",
		                                                                                                              		"CREATE",
		                                                                                                              		"LEFT",
		                                                                                                              		"TIME",
		                                                                                                              		"CROSS",
		                                                                                                              		"LEVEL",
		                                                                                                              		"TIMESTAMP",
		                                                                                                              		"CURRENT",
		                                                                                                              		"LIKE",
		                                                                                                              		"TIMEZONE_HOUR",
		                                                                                                              		"CURRENT_DATE",
		                                                                                                              		"LOCAL",
		                                                                                                              		"TIMEZONE_MINUTE",
		                                                                                                              		"CURRENT_TIME",
		                                                                                                              		"LOWER",
		                                                                                                              		"TO",
		                                                                                                              		"CURRENT_TIMESTAMP",
		                                                                                                              		"MATCH",
		                                                                                                              		"TRAILING",
		                                                                                                              		"CURRENT_USER",
		                                                                                                              		"MAX",
		                                                                                                              		"TRANSACTION",
		                                                                                                              		"CURSOR",
		                                                                                                              		"MIN",
		                                                                                                              		"TRANSLATE",
		                                                                                                              		"DATE",
		                                                                                                              		"MINUTE",
		                                                                                                              		"TRANSLATION",
		                                                                                                              		"DAY",
		                                                                                                              		"MODULE",
		                                                                                                              		"TRIM",
		                                                                                                              		"DEALLOCATE",
		                                                                                                              		"MONTH",
		                                                                                                              		"TRUE",
		                                                                                                              		"DEC",
		                                                                                                              		"NAMES",
		                                                                                                              		"UNION",
		                                                                                                              		"DECIMAL",
		                                                                                                              		"NATIONAL",
		                                                                                                              		"UNIQUE",
		                                                                                                              		"DECLARE",
		                                                                                                              		"NATURAL",
		                                                                                                              		"UNKNOWN",
		                                                                                                              		"DEFAULT",
		                                                                                                              		"NCHAR",
		                                                                                                              		"UPDATE",
		                                                                                                              		"DEFERRABLE",
		                                                                                                              		"NEXT",
		                                                                                                              		"UPPER",
		                                                                                                              		"DEFERRED",
		                                                                                                              		"NO",
		                                                                                                              		"USAGE",
		                                                                                                              		"DELETE",
		                                                                                                              		"NONE",
		                                                                                                              		"USER",
		                                                                                                              		"DESC",
		                                                                                                              		"NOT",
		                                                                                                              		"USING",
		                                                                                                              		"DESCRIBE",
		                                                                                                              		"NULL",
		                                                                                                              		"VALUE",
		                                                                                                              		"DESCRIPTOR",
		                                                                                                              		"NULLIF",
		                                                                                                              		"VALUES",
		                                                                                                              		"DIAGNOSTICS",
		                                                                                                              		"NUMERIC",
		                                                                                                              		"VARCHAR",
		                                                                                                              		"DISCONNECT",
		                                                                                                              		"OCTET_LENGTH",
		                                                                                                              		"VARYING",
		                                                                                                              		"DISTINCT",
		                                                                                                              		"OF",
		                                                                                                              		"VIEW",
		                                                                                                              		"DOMAIN",
		                                                                                                              		"ON",
		                                                                                                              		"WHEN",
		                                                                                                              		"DOUBLE",
		                                                                                                              		"ONLY",
		                                                                                                              		"WHENEVER",
		                                                                                                              		"DROP",
		                                                                                                              		"OPEN",
		                                                                                                              		"WHERE",
		                                                                                                              		"ELSE",
		                                                                                                              		"OPTION",
		                                                                                                              		"WITH",
		                                                                                                              		"END",
		                                                                                                              		"OR",
		                                                                                                              		"WORK",
		                                                                                                              		"END",
		                                                                                                              		"EXEC",
		                                                                                                              		"ORDER",
		                                                                                                              		"WRITE",
		                                                                                                              		"ESCAPE",
		                                                                                                              		"OUTER",
		                                                                                                              		"YEAR",
		                                                                                                              		"EXCEPT",
		                                                                                                              		"OUTPUT",
		                                                                                                              		"ZONE",
		                                                                                                              		"EXCEPTION",
		                                                                                                              		"ABSOLUTE",
		                                                                                                              		"FOUND",
		                                                                                                              		"PRESERVE",
		                                                                                                              		"ACTION",
		                                                                                                              		"FREE",
		                                                                                                              		"PRIOR",
		                                                                                                              		"ADMIN",
		                                                                                                              		"GENERAL",
		                                                                                                              		"PRIVILEGES",
		                                                                                                              		"AFTER",
		                                                                                                              		"GET",
		                                                                                                              		"READS",
		                                                                                                              		"AGGREGATE",
		                                                                                                              		"GLOBAL",
		                                                                                                              		"REAL",
		                                                                                                              		"ALIAS",
		                                                                                                              		"GO",
		                                                                                                              		"RECURSIVE",
		                                                                                                              		"ALLOCATE",
		                                                                                                              		"GROUPING",
		                                                                                                              		"REF",
		                                                                                                              		"ARE",
		                                                                                                              		"HOST",
		                                                                                                              		"REFERENCING",
		                                                                                                              		"ARRAY",
		                                                                                                              		"HOUR",
		                                                                                                              		"RELATIVE",
		                                                                                                              		"ASSERTION",
		                                                                                                              		"IGNORE",
		                                                                                                              		"RESULT",
		                                                                                                              		"AT",
		                                                                                                              		"IMMEDIATE",
		                                                                                                              		"RETURNS",
		                                                                                                              		"BEFORE",
		                                                                                                              		"INDICATOR",
		                                                                                                              		"ROLE",
		                                                                                                              		"BINARY",
		                                                                                                              		"INITIALIZE",
		                                                                                                              		"ROLLUP",
		                                                                                                              		"BIT",
		                                                                                                              		"INITIALLY",
		                                                                                                              		"ROUTINE",
		                                                                                                              		"BLOB",
		                                                                                                              		"INOUT",
		                                                                                                              		"ROW",
		                                                                                                              		"BOOLEAN",
		                                                                                                              		"INPUT",
		                                                                                                              		"ROWS",
		                                                                                                              		"BOTH",
		                                                                                                              		"INT",
		                                                                                                              		"SAVEPOINT",
		                                                                                                              		"BREADTH",
		                                                                                                              		"INTEGER",
		                                                                                                              		"SCROLL",
		                                                                                                              		"CALL",
		                                                                                                              		"INTERVAL",
		                                                                                                              		"SCOPE",
		                                                                                                              		"CASCADED",
		                                                                                                              		"ISOLATION",
		                                                                                                              		"SEARCH",
		                                                                                                              		"CAST",
		                                                                                                              		"ITERATE",
		                                                                                                              		"SECOND",
		                                                                                                              		"CATALOG",
		                                                                                                              		"LANGUAGE",
		                                                                                                              		"SECTION",
		                                                                                                              		"CHAR",
		                                                                                                              		"LARGE",
		                                                                                                              		"SEQUENCE",
		                                                                                                              		"CHARACTER",
		                                                                                                              		"LAST",
		                                                                                                              		"SESSION",
		                                                                                                              		"CLASS",
		                                                                                                              		"LATERAL",
		                                                                                                              		"SETS",
		                                                                                                              		"CLOB",
		                                                                                                              		"LEADING",
		                                                                                                              		"SIZE",
		                                                                                                              		"COLLATION",
		                                                                                                              		"LESS",
		                                                                                                              		"SMALLINT",
		                                                                                                              		"COMPLETION",
		                                                                                                              		"LEVEL",
		                                                                                                              		"SPACE",
		                                                                                                              		"CONNECT",
		                                                                                                              		"LIMIT",
		                                                                                                              		"SPECIFIC",
		                                                                                                              		"CONNECTION",
		                                                                                                              		"LOCAL",
		                                                                                                              		"SPECIFICTYPE",
		                                                                                                              		"CONSTRAINTS",
		                                                                                                              		"LOCALTIME",
		                                                                                                              		"SQL",
		                                                                                                              		"CONSTRUCTOR",
		                                                                                                              		"LOCALTIMESTAMP",
		                                                                                                              		"SQLEXCEPTION",
		                                                                                                              		"CORRESPONDING",
		                                                                                                              		"LOCATOR",
		                                                                                                              		"SQLSTATE",
		                                                                                                              		"CUBE",
		                                                                                                              		"MAP",
		                                                                                                              		"SQLWARNING",
		                                                                                                              		"CURRENT_PATH",
		                                                                                                              		"MATCH",
		                                                                                                              		"START",
		                                                                                                              		"CURRENT_ROLE",
		                                                                                                              		"MINUTE",
		                                                                                                              		"STATE",
		                                                                                                              		"CYCLE",
		                                                                                                              		"MODIFIES",
		                                                                                                              		"STATEMENT",
		                                                                                                              		"DATA",
		                                                                                                              		"MODIFY",
		                                                                                                              		"STATIC",
		                                                                                                              		"DATE",
		                                                                                                              		"MODULE",
		                                                                                                              		"STRUCTURE",
		                                                                                                              		"DAY",
		                                                                                                              		"MONTH",
		                                                                                                              		"TEMPORARY",
		                                                                                                              		"DEC",
		                                                                                                              		"NAMES",
		                                                                                                              		"TERMINATE",
		                                                                                                              		"DECIMAL",
		                                                                                                              		"NATURAL",
		                                                                                                              		"THAN",
		                                                                                                              		"DEFERRABLE",
		                                                                                                              		"NCHAR",
		                                                                                                              		"TIME",
		                                                                                                              		"DEFERRED",
		                                                                                                              		"NCLOB",
		                                                                                                              		"TIMESTAMP",
		                                                                                                              		"DEPTH",
		                                                                                                              		"NEW",
		                                                                                                              		"TIMEZONE_HOUR",
		                                                                                                              		"DEREF",
		                                                                                                              		"NEXT",
		                                                                                                              		"TIMEZONE_MINUTE",
		                                                                                                              		"DESCRIBE",
		                                                                                                              		"NO",
		                                                                                                              		"TRAILING",
		                                                                                                              		"DESCRIPTOR",
		                                                                                                              		"NONE",
		                                                                                                              		"TRANSLATION",
		                                                                                                              		"DESTROY",
		                                                                                                              		"NUMERIC",
		                                                                                                              		"TREAT",
		                                                                                                              		"DESTRUCTOR",
		                                                                                                              		"OBJECT",
		                                                                                                              		"TRUE",
		                                                                                                              		"DETERMINISTIC",
		                                                                                                              		"OLD",
		                                                                                                              		"UNDER",
		                                                                                                              		"DICTIONARY",
		                                                                                                              		"ONLY",
		                                                                                                              		"UNKNOWN",
		                                                                                                              		"DIAGNOSTICS",
		                                                                                                              		"OPERATION",
		                                                                                                              		"UNNEST",
		                                                                                                              		"DISCONNECT",
		                                                                                                              		"ORDINALITY",
		                                                                                                              		"USAGE",
		                                                                                                              		"DOMAIN",
		                                                                                                              		"OUT",
		                                                                                                              		"USING",
		                                                                                                              		"DYNAMIC",
		                                                                                                              		"OUTPUT",
		                                                                                                              		"VALUE",
		                                                                                                              		"EACH",
		                                                                                                              		"PAD",
		                                                                                                              		"VARCHAR",
		                                                                                                              		"END",
		                                                                                                              		"EXEC",
		                                                                                                              		"PARAMETER",
		                                                                                                              		"VARIABLE",
		                                                                                                              		"EQUALS",
		                                                                                                              		"PARAMETERS",
		                                                                                                              		"WHENEVER",
		                                                                                                              		"EVERY",
		                                                                                                              		"PARTIAL",
		                                                                                                              		"WITHOUT",
		                                                                                                              		"EXCEPTION",
		                                                                                                              		"PATH",
		                                                                                                              		"WORK",
		                                                                                                              		"EXTERNAL",
		                                                                                                              		"POSTFIX",
		                                                                                                              		"WRITE",
		                                                                                                              		"FALSE",
		                                                                                                              		"PREFIX",
		                                                                                                              		"YEAR",
		                                                                                                              		"FIRST",
		                                                                                                              		"PREORDER",
		                                                                                                              		"ZONE",
		                                                                                                              		"FLOAT",
		                                                                                                              		"PREPARE"
		                                                                                                              };

		private static readonly object sync = new object();
		private static HashSet<string> builtInFunctionNames;

		private static CompiledGrammar compiledGrammar;
		private static SemanticTypeActions<SqlToken> semanticActions;

		private static XPathDocument LoadCommonObjectsXml() {
			using (Stream stream = typeof(ScriptParser).Assembly.GetManifestResourceStream(typeof(ScriptParser), "SqlCommonObjects.xml")) {
				Debug.Assert(stream != null);
				return new XPathDocument(stream);
			}
		}

		internal static CompiledGrammar GetGrammar() {
			lock (sync) {
				if (compiledGrammar == null) {
					compiledGrammar = CompiledGrammar.Load(typeof(ScriptParser), "ModuleStoreSQL.cgt");
				}
				return compiledGrammar;
			}
		}

		public static SemanticTypeActions<SqlToken> GetSemanticActions() {
			lock (sync) {
				if (semanticActions == null) {
					semanticActions = new SemanticTypeActions<SqlToken>(GetGrammar());
					semanticActions.Initialize();
				}
				return semanticActions;
			}
		}

		public static bool IsReservedWord(string name) {
			return reservedWords.Contains(name);
		}

		public static bool IsBuiltInFunctionName(string functionName) {
			if (builtInFunctionNames == null) {
				// we don't care about race conditions here; in the worst case the set is created multiple times
				HashSet<string> staging = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
				XPathNavigator navigator = commonObjects.CreateNavigator();
				Debug.Assert(navigator.NameTable != null);
				XmlNamespaceManager resolver = new XmlNamespaceManager(navigator.NameTable);
				resolver.AddNamespace("sco", "http://tempuri.org/SqlCommonObjects.xsd");
				foreach (XPathNavigator nav in navigator.Select("/sco:SqlCommonObjects/sco:Category/sco:Objects/sco:Function[not((sco:NoBraces='true') or starts-with(sco:Name, '@'))]/sco:Name/text()", resolver)) {
					staging.Add(nav.Value);
				}
				builtInFunctionNames = staging;
			}
			return builtInFunctionNames.Contains(functionName);
		}

		public static IEnumerable<Statement> Parse(string sql) {
			using (StringReader reader = new StringReader(sql)) {
				return Parse(reader);
			}
		}

		public static IEnumerable<Statement> Parse(TextReader sql) {
			SemanticProcessor<SqlToken> processor = new SemanticProcessor<SqlToken>(sql, GetSemanticActions());
			ParseMessage parseMessage = processor.ParseAll();
			if (parseMessage != ParseMessage.Accept) {
				throw new ArgumentException(string.Format("The supplied SQL could not be parsed: {0} at {1}", parseMessage, ((IToken)processor.CurrentToken).Position));
			}
			return (IEnumerable<Statement>)processor.CurrentToken;
		}
	}
}